id: opecha:P000593
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5812
  title: ཁྱབ་བདག་འཁོར་ལོའི་དབང་ཕྱུག་ངག་དབང་སྐལ་ལྡན་རྒྱ་མཚོའི་རྣམ་ཐར་ཀུན་བཟང་སྤྱོད་ཚུལ་སྣང་བའི་སྒྲོན་མེ་
  volume: ''
  author: ''
