id: I5102B1FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T19:04:25+00:00'
last_modified: '2022-06-07T12:24:26.542731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5812
  title: ཁྱབ་བདག་འཁོར་ལོའི་དབང་ཕྱུག་ངག་དབང་སྐལ་ལྡན་རྒྱ་མཚོའི་རྣམ་ཐར་ཀུན་བཟང་སྤྱོད་ཚུལ་སྣང་བའི་སྒྲོན་མེ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5741':
      image_group_id: I1KG5828
      title: ''
      total_pages: 400
      order: 1
      base_file: 5741.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
